[tool.isort]
profile = "black"

[project]
name = "deploy"
version = ""
description = ""
authors = [{ name = "Zane Dufour", email = "zane@znd4.me" }]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
