exclude: ^vendors$
repos:
  - repo: https://github.com/awslabs/git-secrets/
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff-format
  # pipe changed fish files through fish -c fish_indent (using system-installed fish)
  - repo: https://github.com/znd4/pre-commit-fish
    rev: 47fba3824b49387e9fefc61423c7a25ac4022088
    hooks:
      - id: fish_indent
      - id: fish_syntax
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
      - id: stylua # or stylua-system / stylua-github
