repos:
  - repo: https://github.com/awslabs/git-secrets/
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff-format
  # pipe changed fish files through fish -c fish_indent (using system-installed fish)
  - repo: local
    hooks:
      - id: fish_indent
        name: Format fish scripts with fish_indent
        language: system
        entry: fish -c fish_indent
        types: [fish]
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
      - id: stylua # or stylua-system / stylua-github
