repos:
  - repo: https://github.com/awslabs/git-secrets/
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.14.1
    hooks:
      - id: stylua # or stylua-system / stylua-github
