#!/usr/bin/env sh
set -xe
cd "$(dirname "$0")"

# run `apt-get update` iff `apt-get` is a valid command
command -v apt-get && apt-get update && apt-get install -y \
	parallel \
	stow
xargs -I {} stow --adopt {} ::: <<EOF
asdf
autostart
bash
git
go
macos
python
scripts
tabby
vim
vscode
xdg-config
zsh
EOF
git stash
~/.config/yadm/bootstrap
