#!/usr/bin/env sh
set -xe
cd "$(dirname "$0")"

. ./install_homebrew.sh
brew install \
	parallel \
	stow

parallel --verbose stow --adopt {} ::: <<EOF
asdf
autostart
bash
git
go
macos
python
scripts
tabby
vim
vscode
xdg-config
zsh
EOF
git stash
~/.config/yadm/bootstrap
