name:                kmonad
version:             0.1.0
synopsis:            Advanced keyboard remapping utility
license:             MIT
author:              "David Janssen"
maintainer:          "janssen.dhj@gmail.com"

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base
  - bytestring
  - cereal
  - containers
  - exceptions
  - hashable
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - process
  - text
  - time
  - unagi-chan
  - unix
  - unliftio
  - unordered-containers

c-sources:
  - c_src/keyio.c

library:
  source-dirs: src

executables:
  kmonad:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kmonad
