resolver: lts-14.7
packages:
- .
# extra-deps:
#
#   Currently not required. Leaving this comment in case static-haskell-nix has
#   problems in the future. If it cannot find packages, perhaps adding them here
#   can fix this.
