FROM python:3.9

install:
	RUN echo "foo" > ./bar.txt
	RUN python -m venv /venv
	# This fixed a weird "permission denied" error
	RUN /venv/bin/python -m pip install pyinfra
	COPY install.py .
	
	# ssh setup
	RUN mkdir ~/.ssh

	# Set StrictHostKeyChecking to no
	ARG IP
	RUN printf "Host ${IP}\n\tStrictHostKeyChecking no" >> ~/.ssh/config
	RUN cat ~/.ssh/config

	# Add to known_hosts
	ARG KNOWN_HOSTS
	RUN echo $KNOWN_HOSTS >> ~/.ssh/known_hosts

	ARG PASSWORD
	RUN exit 1
	RUN /venv/bin/python -m pyinfra \
		--user=zane \
		--ssh-password=$PASSWORD \
		--port=22 \
		$IP \
		install.py \
		-vvv 

